### ISSUE TITLE
Any active development?

### ISSUE THREAD

**Issue by drewes** [dbrandonjohnson/logicalprocurement#1]
Have you managed to upgrade the project to rails 3?

**Comment by dbrandonjohnson** [comment]
I haven't.  When i started this project it was an actual project for a client of mine but then they decided that coupa in its current state would work for them so I shelved the project and I haven't been able to get to it because of the effort required.

**Comment by drewes** [comment]
Thanks for getting back to me.

I’ve ended looking at Odoo as an alternative. Has some great modules and his under active development.

Am 06.08.2014 um 19:37 schrieb dbrandonjohnson <notifications@github.com<mailto:notifications@github.com>>:

I haven't. When i started this project it was an actual project for a client of mine but then they decided that coupa in its current state would work for them so I shelved the project and I haven't been able to get to it because of the effort required.
